### ISSUE TITLE
Allow default language to be saved

### ISSUE THREAD

**Issue by Cogiva** [biybl/biybl#10]
Allow users to save default language so that selection is only required once.

**Comment by gerv** [comment]
Yep - an "always use this language" button at the bottom of the page which stores the language choice in a cookie, and so visiting the well-known URL simply brings up the passage in that language. 

The "choose a different language" button at the bottom remains; if it's pressed, then the cookie is forgotten, and the user needs to lock the language again if they want to go back to automatically loading a particular one. (We need a way to easily unlock this for the "church tablet" use case, in case someone accidentally presses it.)

**Comment by gerv** [comment]
Another option would be to have the chosen language always saved and reused, and instead have a button at the bottom "never remember chosen language on this device". When that was pressed, it would set a cookie which said _not_ to save the language. You would then press it, once, on tablets and other shared devices, but the language choice would auto-save for personal devices. This might be a better UX.
