### ISSUE TITLE
Add saved sermon notes along side the verses

### ISSUE THREAD

**Issue by Cogiva** [biybl/biybl#17]
Add a section (formatable) to save sermon notes in to the DB.

**Comment by gerv** [comment]
Yes - we need a rich text editor plugin so people can do headings an bullets. (Perhaps we should implement a restriction that every bulleted list has to have exactly 3 points ;-) ("It's not true that every sermon has to have 3 points but generally, 2 is not enough, and 4 is too many.")

Even if the sermon notes are only in English (I think we'd probably just support one version of them to start with?), people with limited English can often puzzle them out, given time. Heck, we could even use a JS dictionary server plugin so people could mouse over words to get a definition.
